### ISSUE TITLE
NewsEye dataset question

### ISSUE THREAD

**Issue by stefan-it** [EMBEDDIA/stacked-ner#3]
Hi @EmanuelaBoros ,

thanks for releasing the code!

We have tried to reproduce the results from the ["Alleviating Digitization Errors in Named Entity Recognition
for Historical Documents"](https://aclanthology.org/2020.conll-1.35.pdf) and could unfortunately not reproduce them for German.

After comparing the dataset statistics from the original NewsEye 1.0 dataset paper ["A Multilingual Dataset for Named Entity Recognition, Entity Linking and Stance Detection in Historical Newspapers](https://zenodo.org/record/4694466#.YJR20qE6-bi),
it seems that at least two versions of NewsEye dataset were used.

From the NewsEye 1.0 dataset paper, the following statistics are presented:

![image](https://user-images.githubusercontent.com/20651387/124931121-32b1c680-e002-11eb-8c6c-7145a56fcf44.png)

From the CoNLL-paper these statistics are shown:

![image](https://user-images.githubusercontent.com/20651387/124931232-4c530e00-e002-11eb-943a-4cd50456ee60.png)

So there's a big difference between the used number of entites - here's a comparison of total number of instances:

| Paper | LOC | ORG | PERS | PROD
| -------- | ------ | ------- | -------- | ---------
| NewsEye 1.0 Paper | 5,904 | 3,370 | 3,500 | 44
| CoNLL-Paper | 5,443 | 3,730 | 3,231 | 71

I think that another (maybe cleaned) version of NewsEye NER dataset is used in the CoNLL-paper, so I would like to ask, if you could provide this version.

Many thanks in advance,

Stefan

**Comment by EmanuelaBoros** [comment]
Hello @stefan-it,

Sorry for the late reply. Can I ask what results you tried to reproduce, more exactly, and what are the results that you obtained?
Second, there are indeed two versions of the NewsEye dataset, but for this, I'll come back later with details.

Best,
Emanuela

**Comment by EmanuelaBoros** [comment]
Hello @stefan-it,

There are two NewsEye dataset versions, V1 (CoNLL paper) and V2 (final version used in SIGIR paper which is slightly increased). NewsEye V2 (SIGIR) has undergone a new distribution into train (80%) dev (10%) test (10%). Only NewsEye V2 is available at https://zenodo.org/record/4573313#.YD5FIdzjKUk. NewsEye V1 (CoNLL) is not available.

Thanks for your interest. Let me know how I can help to reproduce the results.

**Comment by stefan-it** [comment]
Hi @EmanuelaBoros ,

thanks for the explanations! I tried to reach the results mentioned in the CoNLL paper with the Zenodo dataset, but now it is clear why I couldn't reproduce it. 

I was able to reproduce the result mentioned in the SIGIR paper with the implementation in this repo - thanks for your help :hugs:
